name: API Diff on Merge to Master

on:
  pull_request:
    types: [closed] # Запускаем при закрытии PR
    branches:
      - master # Убедитесь, что это ваша основная ветка (может быть main)

jobs:
  generate-api-diff:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest # Используем последнюю Ubuntu

    steps:
      - name: Checkout base branch state (before merge)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }} # SHA коммита в main ДО мерджа
          path: 'base' # Клонируем в отдельную папку 'base'

      - name: Checkout head branch state (after merge)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }} # SHA коммита ПОСЛЕ мерджа
          path: 'head' # Клонируем в отдельную папку 'head'

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Ваша версия .NET SDK

      # --- Генерация Swagger для состояния ДО мерджа ---
      - name: Build base project
        run: dotnet build ./base/Api-version/Api-version.csproj --configuration Release

      - name: Install Swashbuckle CLI (if needed)
        run: dotnet tool install -g Swashbuckle.AspNetCore.Cli || true

      - name: Generate Swagger (base)
        run: export PATH="$HOME/.dotnet/tools:$PATH" && dotnet swagger tofile --output ./swagger-base.json ./base/Api-version/bin/Release/net8.0/Api-version.dll v1

      # --- Генерация Swagger для состояния ПОСЛЕ мерджа ---
      - name: Build head project
        # Указываем правильный путь к проекту в папке head
        run: dotnet build ./head/Api-version/Api-version.csproj --configuration Release

      - name: Generate Swagger (head)
        run: export PATH="$HOME/.dotnet/tools:$PATH" && dotnet swagger tofile --output ./swagger-head.json ./head/Api-version/bin/Release/net8.0/Api-version.dll v1

      # --- Сравнение и генерация отчета ---
      - name: Setup Node.js (for openapi-diff npm package)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install openapi-diff
        run: npm install -g @openapitools/openapi-diff-cli

      - name: Run openapi-diff and generate HTML report
        # Добавляем || true, чтобы шаг не падал при наличии отличий
        run: openapi-diff ./swagger-base.json ./swagger-head.json --html report.html || true

      # --- Сохранение отчета ---
      - name: Upload HTML Diff Report
        uses: actions/upload-artifact@v4
        with:
          name: api-diff-report-${{ github.event.pull_request.number }}
          path: report.html

      # --- (Опционально) Отправка в Telegram ---
      # ... (остается без изменений) ...
